#!/bin/bash
# chkconfig: - 64 36
# description: NetApp OnCommand System Manager

usage() {
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
}

[ $# -gt 0 ] || usage

ACTION=$1

INSTALL_DIR=/opt/NetApp/oncommand_system_manager/2.0/
PIDFILE=/var/run/netapp/system_manager.pid
RUN_AS_USER=netapp
LOG_FILE=$INSTALL_DIR/last.log

RUN_CMD="java -Djava.awt.headless=true -jar SystemManager.jar"

if [ -n "$RUN_AS_USER" ] ; then
    RUNNER="su - $RUN_AS_USER -c"
else
    RUNNER="sh -c"
fi

PDIR=`dirname $PIDFILE`
if [ ! -d $PDIR ] ; then
    mkdir $PDIR
    [ -n "$RUN_AS_USER" ] && chown -R $RUN_AS_USER:$RUN_AS_USER $PDIR
fi

if [ -f $PIDFILE ] ; then
    PID=`cat $PIDFILE 2>/dev/null`
    if [ -z "$PID" ] || ! ps "$PID" >/dev/null ; then
        echo "NetApp OnCommand System Manager with pid=${PID} is not running - removing old pidfile ${PIDFILE}"
        unset PID
        rm -f $PIDFILE
    fi
fi

case "$ACTION" in
  start)
        echo -n "Starting NetApp OnCommand System Manager... "

        if [ -n "$PID" ] ; then
            echo "Already running!"
            exit 1
        fi

        echo "Ok"

        $RUNNER "nohup sh -c \"cd $INSTALL_DIR && exec $RUN_CMD 2>&1\" >$LOG_FILE 2>/dev/null & umask 022; echo \$! > $PIDFILE"
#        echo "NetApp OnCommand System Manager running, pid=$(cat $PIDFILE)"
        ;;

  stop)
        if [ -n "$PID" ] ; then
            echo -n "Shutting down NetApp OnCommand System Manager, pid=$PID... "
            kill $PID 2>/dev/null
            sleep 2
            if kill -0 $PID 2>/dev/null; then
                sleep 1
                kill -9 $PID 2>/dev/null
            fi
            rm -f $PIDFILE
            echo "Ok"
        else
            echo "NetApp OnCommand System Manager is currently not running."
        fi
        ;;

  restart)
        $0 stop $*
        sleep 5
        $0 start $*
        ;;

  status)
        if [ -n "$PID" ] ; then
            echo "NetApp OnCommand System Manager running, pid=$PID"
            exit 0
        else
            echo "NetApp OnCommand System Manager is currently not running."
            exit 1
        fi
        ;;

*)
        usage
        ;;
esac

exit 0